server {
    server_name ostapdotcenko.ru www.ostapdotcenko.ru;
    root /var/www/ostapdotcenko.ru;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ostapdotcenko.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ostapdotcenko.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.ostapdotcenko.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = ostapdotcenko.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name ostapdotcenko.ru www.ostapdotcenko.ru;
    return 404; # managed by Certbot
}
